#!/bin/sh
set -e;

plat_gui="$(
            python3 -c '
import platform
print(platform.platform().split("-")[0])
'
)-gui";

pip-compile --strip-extras --quiet --upgrade --allow-unsafe --no-emit-index-url
pip-compile --strip-extras --quiet --upgrade --allow-unsafe --no-emit-index-url --extra "${plat_gui}" -o "${plat_gui}.requirements.txt"
pip-compile --strip-extras --quiet --upgrade --allow-unsafe --no-emit-index-url --extra dev -o dev-requirements.txt
