"""
This is a setup.py script generated by py2applet

Usage:
    python py2app_setup.py py2app
"""

import os
from setuptools import setup
from encrust_setup import description

setup(**description.setupOptions())
