#!/bin/bash -ex

mypy ./src;

if [ -e ./dist/TestPomodouroboros.app ]; then
    # rm -fr ./dist/TestPomodouroboros.app;
    echo 'already existed';
else
    TEST_MODE=YES encrust devalias;
fi;

exec ./dist/TestPomodouroboros.app/Contents/MacOS/TestPomodouroboros;

